image: 
  file: .gitpod.Dockerfile
  
  
tasks:
  - init: 'set +x; clear'
    command: |
      set +x; clear
         
      source <(curl -s -L http://gitpod-extras.bobdot.me:4444/tooling) 
      
      export PATH=/workspace/bob/plugins/kubectl:$PATH
      exec /bin/bash
