FROM ubuntu:focal

LABEL MAINTAINER "Bob Liotta" <bob@bobdot.me>

RUN echo 'debconf debconf/frontend select Noninteractive' |  debconf-set-selections && \
    apt-get --quiet --yes update  && \
    apt-get --quiet --yes install --no-install-recommends unzip fio iperf3 openssh-client openssh-server rsync curl wget iputils-ping dnsutils vim-tiny apt-utils pciutils nfs-ganesha nfs-ganesha-vfs systemctl rsync socat ldap-utils screen&& \
    apt-get --quiet --yes upgrade && \
    apt-get --quiet --yes clean all && \
    apt-get --quiet --yes autoremove && \
    wget --quiet --no-check-certificate https://storage.googleapis.com/kubernetes-release/release/$(wget --quiet --no-check-certificate https://storage.googleapis.com/kubernetes-release/release/stable.txt --output-document -)/bin/linux/amd64/kubectl  && \
    mv kubectl /usr/local/bin/kubectl && \
    chmod 775 /usr/local/bin/kubectl && \
    mkdir work && \
    cd work && \
    export RELEASE="3.3.8" && \
    wget --quiet --no-check-certificate https://github.com/etcd-io/etcd/releases/download/v${RELEASE}/etcd-v${RELEASE}-linux-amd64.tar.gz && \
    tar zxf etcd-v${RELEASE}-linux-amd64.tar.gz && \
    cd etcd-v${RELEASE}-linux-amd64 && \
    cp ./etcd* /usr/local/bin/. && \
    cd ../../ && \  
    cd /etc/alternatives && mv ./* /usr/bin/. && \
    cd /tmp &&  \
    mkdir websocketd && \
    cd /tmp/websocketd && \
    wget --quiet --no-check-certificate  https://github.com/joewalnes/websocketd/releases/download/v0.4.1/websocketd-0.4.1-linux_amd64.zip && \
    unzip websocketd-0.4.1-linux_amd64.zip && \
    mv websocketd /usr/bin/websocketd && \
    rm -rf /tmp/websocketd && \
    chmod 755 /usr/bin/websocketd && \
    rm -rf /tmp/websocketd* && \
    mkdir -p /app/cgi /app/docs /app/ws && \
    rm -rf work

ADD files/entrypoint-core.sh /files/entrypoint.sh
ADD files/.bashrc /root/.bashrc
ADD files/info /usr/bin/info
ADD files/app/cgi/work.cgi /app/cgi/work.cgi
ADD files/app/docs/index.html /app/docs/index.html
Add files/app/ws/work.ws /app/ws/work.ws
ADD files/wstest.sh /usr/bin/wstest
ADD files/ganesha.conf /etc/ganesha/ganesha.conf
ADD files/rsyncd.conf /etc/rsyncd.conf

RUN chmod 775 files/entrypoint.sh \
              root/.bashrc \
              usr/bin/info \
              usr/bin/wstest \
              app/cgi/work.cgi \ 
              app/ws/work.ws

EXPOSE 8873
EXPOSE 8080

ENTRYPOINT [ "/files/entrypoint.sh" ]
